# Evidence Report — {{type}} — {{date}}

## Metadata
- **Multisig:** `{{multisig_address}}`
- **Date (UTC):** {{date}}
- **Type:** {{type}}
- **Facilitator:** {{facilitator}}
- **Evidence keeper:** {{evidence_keeper}}
- **Ceremony ID:** {{ceremony_id}}

## Participants
| # | Name | Role | Address | Verification | Signed attestation |
|---|------|------|---------|--------------|--------------------|
{{#participants}}
| {{index}} | {{name}} | {{role}} | `{{address}}` | {{verification}} | {{signed}} |
{{/participants}}

## Proposals reviewed
| # | Proposal ID | Description | Verdict | Signatures collected |
|---|-------------|-------------|---------|----------------------|
{{#proposals}}
| {{index}} | {{id}} | {{description}} | {{verdict}} | {{signatures}} |
{{/proposals}}

## Findings / red flags
{{#findings}}
- {{.}}
{{/findings}}

## Artifacts
- Audit snapshot: `{{audit_snapshot}}`
- Decoded proposals: `{{decoded_proposals}}`
- Simulation outputs: `{{simulation_outputs}}`
- Attestation messages: `{{attestations}}`

## Follow-up actions
{{#actions}}
- [ ] {{.}}
{{/actions}}

## Sign-off
| Name | Signature / hash | Date |
|------|------------------|------|
{{#signoff}}
| {{name}} | `{{signature}}` | {{date}} |
{{/signoff}}

---
*Generated by solana-multisig-ceremony-skill tools. Do not store private keys or seed phrases here.*
